version: "3.3"

services:
  db:
    container_name: sib_dev_db
    restart: always
    image: postgres:11
    env_file:
      - .env
#    volumes:
#    - /app/postgres:/var/lib/postgresql/data
#if u need to save data after reboot application apply  this volumes

  app_migration:
    build: .
    restart: on-failure
    container_name: sib_dev_db_migration
    command: python manage.py migrate
    depends_on:
      - db
    env_file:
      - .env

  web:
    build: .
    restart: always
    container_name: testcase_app
    command: uwsgi --http :8000 --module main.wsgi
    ports:
    - "8000:8000"

    depends_on:
      - db
      - app_migration
    env_file:
      - .env
