# Generated by Django 3.2 on 2021-04-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deals',
            old_name='date',
            new_name='date_time',
        ),
    ]
